# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200616_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 13, 28, 23, 282565, tzinfo=utc)),
        ),
    ]
