# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200616_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
