# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200620_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LPM', 'LPM'), ('NgaduBako', 'NgaduBako')], max_length=200),
        ),
    ]
